-- 코드를 입력하세요
WITH T AS(
    SELECT O.PRODUCT_ID, SUM(O.SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE O
    GROUP BY PRODUCT_ID
)


SELECT P.PRODUCT_CODE, P.PRICE* T.AMOUNT AS SALES
FROM T
JOIN PRODUCT P ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC