SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND((1-(DP.DISCOUNT_RATE/100))*C.DAILY_FEE*30 ,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN으로 할인율 적용
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON C.CAR_TYPE = DP.CAR_TYPE
AND DP.DURATION_TYPE = '30일 이상'
-- WHERE에서 차종 필터
WHERE C.CAR_TYPE IN ('세단','SUV')
-- NOT EXISTS로 11월에 겹치는 대여 기록 제거
AND NOT EXISTS(
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    WHERE C.CAR_ID = RH.CAR_ID 
    AND (RH.START_DATE<='2022-11-30' AND RH.END_DATE>='2022-11-01' )
)

-- WHERE에서 금액 필터
AND   ROUND((1-(DP.DISCOUNT_RATE/100))*C.DAILY_FEE*30 ,0)>=500000
AND   ROUND((1-(DP.DISCOUNT_RATE/100))*C.DAILY_FEE*30,0)<2000000

-- ORDER BY
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;