-- 년, 월, 성별 별로 상품을 구매한 회원수
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, GENDER,COUNT(DISTINCT USER_ID)  AS USERS
FROM ONLINE_SALE 
LEFT JOIN USER_INFO USING(USER_ID)
WHERE gender IS NOT NULL
GROUP BY YEAR(sales_date), MONTH(sales_date), GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC