-- 코드를 입력하세요
WITH T AS(
SELECT O.PRODUCT_ID, SUM(O.AMOUNT) AS AMOUNT
FROM FOOD_ORDER O
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
)
SELECT T.PRODUCT_ID, P.PRODUCT_NAME, T.AMOUNT*P.PRICE AS TOTAL_SALES
FROM T
JOIN FOOD_PRODUCT P
ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC