-- 코드를 입력하세요
WITH T AS (
    SELECT RH.HISTORY_ID, RH.CAR_ID, C.CAR_TYPE as CAR_TYPE, C.DAILY_FEE,
    DATEDIFF(RH.END_DATE, RH.START_DATE)+1 AS DURATION,
    CASE
        WHEN DATEDIFF(RH.END_DATE, RH.START_DATE)+1>=90 THEN '90일 이상'
        WHEN DATEDIFF(RH.END_DATE, RH.START_DATE)+1>=30 THEN '30일 이상'
        WHEN DATEDIFF(RH.END_DATE, RH.START_DATE)+1>=7 THEN '7일 이상'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = RH.CAR_ID
    WHERE C.CAR_TYPE="트럭"
)


SELECT HISTORY_ID,
ROUND(DURATION*(1-IFNULL(DP.discount_rate,0)/100)*DAILY_FEE,0 )AS FEE
FROM T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
on DP.DURATION_TYPE=T.DURATION_TYPE AND DP.CAR_TYPE = T.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC