-- 코드를 입력하세요
WITH T AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS FIRST_HALF_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), K AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT K.FLAVOR
FROM K
JOIN T on K.FLAVOR = T.FLAVOR
GROUP BY T.FLAVOR
ORDER BY K.JULY_ORDER + T.FIRST_HALF_ORDER  DESC
LIMIT 3
