SELECT A.ID,A.EMAIL,A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
JOIN SKILLCODES B
ON B.CATEGORY = "Front End"
AND (B.CODE & A.SKILL_CODE)>0
GROUP BY A.ID,A.EMAIL,A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID ASC