-- 코드를 입력하세요
WITH T AS(

SELECT R.MEMBER_ID,
DENSE_RANK() OVER(ORDER BY COUNT(R.MEMBER_ID) DESC) AS RNK
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P
ON P.MEMBER_ID = R.MEMBER_ID
GROUP BY MEMBER_ID

)


SELECT P.MEMBER_NAME ,RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE P
ON P.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT T.MEMBER_ID
    FROM T
    WHERE RNK =1
)

ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC


