-- 코드를 입력하세요
WITH T AS (
    SELECT BOARD_ID,UGB.VIEWS,
    CONCAT("/home/grep/src/",BOARD_ID,"/", UGF.FILE_ID,UGF.FILE_NAME,UGF.FILE_EXT) AS FILE_PATH,
    DENSE_RANK() OVER(ORDER BY UGB.VIEWS DESC) as rnk
    FROM USED_GOODS_BOARD UGB
    JOIN USED_GOODS_FILE UGF
    USING (BOARD_ID)
    ORDER BY UGF.FILE_ID DESC
)

SELECT FILE_PATH 
FROM T
WHERE rnk=1